### ISSUE TITLE
Request to Integrate NV-Embed-v2 Model

### ISSUE THREAD

**Issue by ogkdmr** [argonne-lcf/inference-endpoints#2]
Hi, 

It would be great if we had an embedding model among the inference endpoints. I propose [NV-Embed-v2](https://huggingface.co/nvidia/NV-Embed-v2/tree/main) to be this encoding model because it is currently the SOTA based on the [MTEB suite of benchmarks](https://huggingface.co/spaces/mteb/leaderboard) benchmark. It is particularly performant on retrieval-related tasks, including those related to biomedical domain such as TREC-COVID. 

The model has 7B parameters, 4096 embedding dimension, 32k context window. The weights are in /lus/eagle/projects/argonne_tpc/model_weights directory.

**Comment by atanikan** [comment]
Thanks Ogan for the recommendation. We now have it up and running. Please take a look at the documentation on how to use it.
